name: Update IBEX35 Heatmap Data (daily)

on:
  schedule:
    - cron: '15 17 * * 1-5'   # 17:15 UTC ≈ 18:15 CET (ajústalo si quieres)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: pip install requests beautifulsoup4 lxml

      - name: Run scraper
        run: python scripts/scrape_ibex.py

      - name: Commit & push data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/ibex35.json
          git commit -m "Update IBEX35 data [skip ci]" || echo "No changes"
          git push
